[startup."ovs.init"]
name = "core.system"
running_delay = -1

[startup."ovs.init".args]
name = "/usr/bin/ovsdb-tool"
args = ["create", "/etc/openvswitch/conf.db"]

[startup.ovsdb]
name = "core.system"
after = ["ovs.init"]

[startup.ovsdb.args]
name = "/usr/sbin/ovsdb-server"
args = ["--remote=punix:/var/run/openvswitch/db.sock", "--pidfile=/var/run/openvswitch/ovsdb-server.pid"]

[startup.ovs]
name = "core.system"
after = ["ovsdb"]

[startup.ovs.args]
name = "/usr/sbin/ovs-vswitchd"
args = ["--pidfile=/var/run/openvswitch/ovs-vswitchd.pid"]
